---
- hosts: webserver
  become: yes
  become_method: sudo
  vars:
    http_port: 80
    email: howdy140@gmail.com
    domain: myfirstgcpchallenge.com
    docroot: /var/www/html

  tasks:

    - name: update apt and install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: install letsencrypt client
      apt:
        name: python-certbot-nginx
        state: latest

    - name: create index file
      file:
        path: "{{ docroot }}/index.html"
        state: touch
      ignore_errors: yes

    - name: add http server block for domain
      template:
        src: ./nginx-default.j2
        dest: /etc/nginx/sites-available/{{ domain }}

    - name: enable new server block
      file:
        src: /etc/nginx/sites-available/{{ domain }}
        dest: /etc/nginx/sites-enabled/{{ domain }}
        state: link
      ignore_errors: yes

    - name: reload nginx
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes

    - name: fetch & install LE certificate
      command: /usr/bin/certbot --authenticator webroot --webroot-path {{ docroot }} -m {{ email }} -d {{ domain }} --installer nginx --non-interactive --agree-tos
